#!/usr/bin/env bash

# https://stackoverflow.com/questions/59895/getting-the-source-directory-of-a-bash-script-from-within
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

export DOCKER_STACK_DIR=$DIR/dockerstack
export ROOT_DIR=$DIR

# OSX
## Get IP Address on OSX
IP=$(ipconfig getifaddr en0) #ethernet
if [ -z $IP ]; then
    IP=$(ipconfig getifaddr en1) #wifi
fi

if [ -f .env ]; then
    source .env
else
    echo "You must put an .env file with creds, otherwise it's not gonna work, exiting"
    exit 1
fi

DOCKERCOMPOSE="docker-compose --file $DOCKER_STACK_DIR/docker-compose.yml"
if [ $# -gt 0 ]; then
    case $1 in
        hello)
            echo "Hello Boy"
        ;;
        config)
            echo "Check docker-composer file"
            $DOCKERCOMPOSE config
        ;;
        build)
            echo "build docker-compose"
            $DOCKERCOMPOSE build
        ;;
        start)
            echo "Starting docker stack"
            $DOCKERCOMPOSE up -d
            sh $ROOT_DIR/wpd ip
        ;;
        stop)
            echo "Stopping docker stack"
            bash $ROOT_DIR/wpd dump
            $DOCKERCOMPOSE down -v
        ;;
        bash)
            echo "Exposing bash of Wordpress container"
            $DOCKERCOMPOSE exec wordpress bash
        ;;
        ip)
            echo "Front: "
            echo "http://localhost:${HTTP_PORT}"
            echo "http://$IP:${HTTP_PORT}"
            exit 0
        ;;
        dump)
            echo "Backuping the db"
            $DOCKERCOMPOSE exec db mysqldump -u$MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE > $DOCKER_STACK_DIR/_dockerdb/$MYSQL_DATABASE.sql
            exit 0
        ;;
        import)
            echo "Importing DB"
            cat $DOCKER_STACK_DIR/_dockerdb/$MYSQL_DATABASE.sql | docker exec -i "${PROJECT_NAME}_mysql_1" mysql -u$MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE
        ;;
        sed_sql)
            cp $DOCKER_STACK_DIR/_dockerdb/$MYSQL_DATABASE.sql $DOCKER_STACK_DIR/_dockerdb/$MYSQL_DATABASE._sed.sql
            sed -i -e "s/localhost:$HTTP_PORT/$PRODURI/g" $DOCKER_STACK_DIR/_dockerdb/$MYSQL_DATABASE._sed.sql
            rm $DOCKER_STACK_DIR/_dockerdb/$MYSQL_DATABASE._sed.sql-e
        ;;
        *)
            echo "Unknown command"
            exit 0
        ;;
    esac
else
    echo "Hum, you didn't provide any command"
    exit 0
fi

exit 0