version: '3'

services:
  wordpress:
    container_name: "${PROJECT_NAME}_wp_1"
    build: ${DOCKER_STACK_DIR}/php
    volumes:
      - ${ROOT_DIR}/www/wp:/var/www/html
      - ${DOCKER_STACK_DIR}/php/php.ini:/usr/local/etc/php/conf.d/uploads.ini
    ports:
      - "${HTTP_PORT}:80"
    environment:
      WORDPRESS_DB_NAME: "${MYSQL_DATABASE}"
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: "${MYSQL_USER}"
      WORDPRESS_DB_PASSWORD: "${MYSQL_PASSWORD}"
    restart: always
    depends_on:
      - db
    links:
      - db

  db:
    container_name: "${PROJECT_NAME}_mysql_1"
    image: mysql:5.5
    restart: always
    volumes:
      - ${DOCKER_STACK_DIR}/_dockerdb/:/docker-entrypoint-initdb.d
      - ${DOCKER_STACK_DIR}/mysql:/etc/mysql/conf.d
      - wpd_dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"

  phpmyadmin:
    container_name: "${PROJECT_NAME}_phpmyadmin_1"
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
      - "${PHPMYADMIN_PORT}:80"
    depends_on:
      - db
    links:
      - db

  # node:
  #   container_name: "${PROJECT_NAME}_node_1"
  #   build: ./node
  #   volumes:
  #   - ./www:/var/www

volumes:
  wpd_dbdata:
