version: '3'

services:
  wordpress:
    image: wordpress:latest
    container_name: "${PROJECT_NAME}_wp_1"
    volumes:
      - ../www/wp:/var/www/html
    ports:
      - "${HTTP_PORT}:80"
    environment:
      WORDPRESS_DB_NAME: "${PROJECT_NAME}"
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: "${MYSQL_USER}"
      WORDPRESS_DB_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      WORDPRESS_DB_NAME: "${PROJECT_NAME}"
    restart: always
    depends_on:
      - mysql
    links:
      - mysql

  mysql:
    image: mysql:5.5
    container_name: "${PROJECT_NAME}_db_1"
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${PROJECT_NAME}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
  node:
    container_name: "${PROJECT_NAME}_node_1"
    build: ./node
    volumes:
    - ./www:/var/www



  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "${PROJECT_NAME}_phpmyadmin_1"
    ports:
      - "${PHPMYADMIN_HTTP_PORT}:80"
    depends_on:
      - mysql
    links:
      - mysql:db


volumes:
  dbdata:
